ubah config file CI/CD

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -27,6 +27,9 @@ jobs:
     - name: Build project
       run: yarn build
 
+    - name: List files after build
+      run: ls -alh
+
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
 
@@ -34,11 +37,14 @@ jobs:
       run: docker build -t my-nextjs-app .
 
     - name: Save Docker image as artifact
+      if: always()
       uses: actions/upload-artifact@v3
       with:
         name: my-nextjs-app
-        path: |
-          ./my-nextjs-app.tar
+        path: ./my-nextjs-app.tar
+
+    - name: Check artifact existence
+      run: test -f ./my-nextjs-app.tar && echo "Artifact exists" || echo "Artifact not found"
 
     - name: Download Docker image artifact
       if: always()
